pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git url : "https://github.com/Kunalkthalautiya/AUTOMATED-ML-MD-with-CICD-MONITORING.git", branch : "main"
            }
        }
        stage("Build"){
            steps{
                sh " docker build -t ml_model ."
            }
        }
        stage("Test"){
            steps{
                echo "No Error"
            }
        }
        stage("deploy"){
            steps{
                sh "docker stop ml_model || true"
                sh "docker rm ml_model || true"
                sh " docker run -d -p 5000:5000 --name ml_model ml_model:latest"
            }
        }
    }
}
